language: java
jdk:
  - openjdk8

sudo: required
# https://docs.travis-ci.com/user/customizing-the-build/#Skipping-the-Installation-Step
install: true

branches:
  only:
    - master

cache:
  directories:
    - '$HOME/.m2/repository'

before_install:
  - export CLOUD_SDK_REPO="cloud-sdk-$(lsb_release -c -s)"
  - echo "deb https://packages.cloud.google.com/apt $CLOUD_SDK_REPO main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
  - curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
  - sudo apt-get update && sudo apt-get install -y kubectl google-cloud-sdk google-cloud-sdk-app-engine-java wget unzip
  - wget https://archive.apache.org/dist/maven/maven-3/3.5.0/binaries/apache-maven-3.5.0-bin.zip
  - unzip -qq apache-maven-3.5.0-bin.zip
  - export M2_HOME=$PWD/apache-maven-3.5.0
  - export PATH=$M2_HOME/bin:$PATH
  - apache-maven-3.5.0/bin/mvn -v
  - openssl aes-256-cbc -K $encrypted_70da3b7ebeab_key -iv $encrypted_70da3b7ebeab_iv -in travis-cigrowbit-52554fcb00cd.json.enc -out travis-cigrowbit-52554fcb00cd.json -d

before_script:
    - gcloud auth activate-service-account "travis-ci@growbit-0.iam.gserviceaccount.com" --key-file=travis-cigrowbit-52554fcb00cd.json
    - gcloud config set project growbit-0

script:
  - apache-maven-3.5.0/bin/mvn clean install
  - apache-maven-3.5.0/bin/mvn package
  - apache-maven-3.5.0/bin/mvn appengine:deploy
  - apache-maven-3.5.0/bin/mvn appengine:deployIndex

notifications:
  email: false
